java_library(
    name = "SwapNodes",
    srcs = ["SwapNodes.java"],
    deps = ["//linkedList:LinkedListNode", 
            "//linkedList:LinkedList"],
)

java_test(
    name = "TestSwapNodes",
    srcs = ["TestSwapNodes.java"],
    deps = [":SwapNodes", "//linkedList:LinkedList", "//linkedList:LinkedListNode"],
    test_class = "testSwapNodes.TestSwapNodes",
)