package(default_visibility = ["//visibility:public"])

java_library(
    name = "LinkedList",
    srcs = ["LinkedList.java"],
    deps = [":LinkedListNode"],
)

java_library(
    name = "LinkedListNode",
    srcs = ["LinkedListNode.java"],
)
